# Generated by Django 4.2.16 on 2024-11-11 23:50

from django.db import migrations, models
import toolkit.mailer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailoutJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_at",
                    toolkit.mailer.models.FutureDateTimeField(db_index=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENDING", "Sending"),
                            ("CANCELLING", "Cancelling"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Waiting to start", max_length=255
                    ),
                ),
                ("progress_pct", models.SmallIntegerField(default=0)),
                ("send_count", models.IntegerField(default=0)),
                ("send_html", models.BooleanField()),
                ("subject", models.TextField()),
                ("body_text", models.TextField()),
                ("body_html", models.TextField()),
                (
                    "recipient_filter",
                    models.CharField(blank=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
