# Generated by Django 5.2.14 on 2026-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailoutjob",
            name="body_html",
            field=models.TextField(blank=True),
        ),
    ]
