# Generated by Django 2.2.24 on 2021-11-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_auto_20211126_2147"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="clean_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Safe name of the form field, the label converted to ascii_snake_case",
                max_length=255,
                verbose_name="name",
            ),
        ),
    ]
