# Generated by Django 3.2.18 on 2023-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_formfield_clean_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicarticlepage",
            name="show_on_programme_page",
            field=models.BooleanField(
                default=False,
                help_text="Whether a link to this page will appear alongside the main public programme listings",
                verbose_name="show on programme pages",
            ),
        ),
    ]
