# This compose file is for development and test, not for production deployment!
version: "3.7"
networks:
  toolkit:
    driver: bridge
volumes:
  media_data:
  mariadb_data:
services:
  toolkit:
    networks:
      - toolkit
    image: toolkit:latest
    build: .
    command: ["tk_run", "gunicorn"]
    restart: on-failure
    environment: &commonEnv
      DB_NAME: "toolkit"
      DB_USER: "toolkit"
      DB_PASSWORD: "rubbishpassword"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY: "totallyinsecureandnotverysecretkeywhichiswhythisisunsafe"
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: media_data
        target: /site/media/
  celery:
    networks:
      - toolkit
    image: toolkit:latest
    command: ["tk_run", "celery"]
    restart: on-failure
    environment: *commonEnv
  redis:
    networks:
      - toolkit
    image: redis:7-bullseye
  mariadb:
    networks:
      - toolkit
    image: mariadb:10
    environment:
      MARIADB_USER: toolkit
      MARIADB_PASSWORD: rubbishpassword
      MARIADB_ROOT_PASSWORD: rubbishpassword
      MARIADB_DATABASE: toolkit
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql
