# This compose file is for development and test, not for production deployment!
version: "3.7"
networks:
  toolkit:
    driver: bridge
services:
  toolkit:
    networks:
      - toolkit
    image: toolkit:latest
    build: .
    command: ["tk_run", "gunicorn"]
    restart: on-failure
    environment: &commonEnv
      DB_NAME: "${DB_NAME:-toolkit}"
      DB_USER: "${DB_USER:-toolkit}"
      DB_PASSWORD: "${DB_PASSWORD-devserver_db_password}"
      DB_HOST: ""
      DB_PORT: ""
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY: "${DJANGO_SECRET_KEY:?django secret key not set}"
    ports:
      - target: "8000"
        published: "8000"
        protocol: tcp
    volumes:
      - type: bind
        source: "${MEDIA_PATH:-$PWD/media/}"
        target: /site/media/
      - type: bind
        source: /var/run/mysqld/mysqld.sock
        target: /var/run/mysqld/mysqld.sock
  celery:
    networks:
      - toolkit
    image: toolkit:latest
    command: ["tk_run", "celery"]
    restart: on-failure
    environment: *commonEnv
    volumes:
      - type: bind
        source: /var/run/mysqld/mysqld.sock
        target: /var/run/mysqld/mysqld.sock
  redis:
    networks:
      - toolkit
    image: redis:7-bullseye
