#!/bin/bash

set -e # Abort on errors

if [ $# -eq 0 ] ; then
	echo "Usage: $0 [Path to site root]"
	exit 1
fi

if [ ! -d $1 ] ; then
	echo "Error: $1 is not a directory"
	exit 1
fi

TOOLKIT_PATH=$1

echo "Activate virtualenv"

source $TOOLKIT_PATH/venv/bin/activate

export PYTHONPATH=$PYTHONPATH:$TOOLKIT_PATH
export DJANGO_SETTINGS_MODULE=toolkit.settings

echo "Resetting database"

python $TOOLKIT_PATH/manage.py syncdb
python $TOOLKIT_PATH/manage.py flush --noinput

echo "Importing into django"

python $TOOLKIT_PATH/import_script/import_database.py $TOOLKIT_PATH

echo "Done. Guessing event tags..."

python $TOOLKIT_PATH/import_script/auto_tag.py

echo "Creating users"

python $TOOLKIT_PATH/import_script/create_users.py

echo "Converting app to use south migrations"

python $TOOLKIT_PATH/manage.py convert_to_south diary
python $TOOLKIT_PATH/manage.py convert_to_south members
