# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_showing_event_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='credit',
            field=models.CharField(blank=True, default='Internet scavenged', max_length=256, verbose_name='Image credit'),
        ),
        migrations.AlterField(
            model_name='printedprogramme',
            name='designer',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
