# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20180223_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='terms',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
