# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20171107_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
