# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_volunteer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=64),
        ),
    ]
